### ISSUE TITLE
Fix invoice saving, add locale settings, and use OCAlert

### ISSUE THREAD

**Issue by ilkkalehtinen** [OpusCapita/posting#21]
-Invoice saving is currently broken i.e. multiple posting rows are created incorrectly
-Grid to use locale formatting for numbers, English and German
-OCAlert should be shown when posting is saved

**Comment by pirttpi1** [comment]
Still something small to do.
Either we remove all 'amount', or change Gross Amount -> Gross amount (and have maybe wider column to fit the name)
If the amount on the posting is 0, it should be saved like 0.00, not 0
Should we make sorting so that only one column is sorted (if user changes the sorting to different column, the first sorting is remembered anyways)
Amounts should not be sorted alphabetically.

**Comment by pirttpi1** [comment]
Sorting of cost centers and Accounts should be done by the code and alphabetical sorting.

**Comment by pirttpi1** [comment]
Sorting works, numbers look ok. Line Id field is added.
